import { NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { PrismaClient } from "@/lib/generated/prisma";

const prisma = new PrismaClient();

const DEFAULT_HASHTAG_SETS = [
  {
    name: "Daily Lifestyle",
    category: "Lifestyle",
    icon: "Coffee",
    color: "amber",
    description: "General lifestyle and daily moments",
    hashtags: [
      "#lifestyle",
      "#lifestyleblogger",
      "#dailylife",
      "#everydaymoments",
      "#liveauthentic",
      "#thehappynow",
      "#livethelittlethings",
      "#pursuepretty",
      "#thatsdarling",
      "#flashesofdelight",
      "#myeverydaymagic",
      "#momentsofmine",
      "#nothingisordinary",
      "#theeverydayproject",
      "#lifeunscripted",
      "#slowliving",
      "#simplepleasures",
      "#seekthesimplicity",
      "#embracingtheseasons",
      "#capturinglife",
      "#morningslikethese",
      "#quietmoments",
      "#smallmomentscount",
      "#livemoremagic",
      "#enjoythelittlethings",
      "#makemoments",
      "#seekinspirecreate",
      "#thehappynow",
      "#livecolorfully",
      "#lifeofadventure",
    ],
  },
  {
    name: "Fashion & Style",
    category: "Fashion",
    icon: "Shirt",
    color: "pink",
    description: "Fashion, outfits, and style inspiration",
    hashtags: [
      "#fashion",
      "#fashionblogger",
      "#fashionista",
      "#style",
      "#styleblogger",
      "#ootd",
      "#outfitoftheday",
      "#fashiongram",
      "#instafashion",
      "#fashionable",
      "#fashionstyle",
      "#styleinspo",
      "#fashioninspo",
      "#outfitinspo",
      "#outfitinspiration",
      "#whatiwore",
      "#wiw",
      "#todaysoutfit",
      "#currentlywearing",
      "#fashiondiaries",
      "#stylediaries",
      "#fashionpost",
      "#fashiondaily",
      "#streetstyle",
      "#streetfashion",
      "#lookoftheday",
      "#mylook",
      "#fashionlover",
      "#instastyle",
      "#fashionaddict",
    ],
  },
  {
    name: "Fitness & Workout",
    category: "Fitness",
    icon: "Dumbbell",
    color: "red",
    description: "Fitness, workouts, and healthy living",
    hashtags: [
      "#fitness",
      "#fitnessmotivation",
      "#fitnessjourney",
      "#workout",
      "#workoutmotivation",
      "#gym",
      "#gymlife",
      "#gymmotivation",
      "#fitfam",
      "#fitspo",
      "#fitlife",
      "#getfit",
      "#fitnessgoals",
      "#healthylifestyle",
      "#health",
      "#wellness",
      "#strengthtraining",
      "#cardio",
      "#exercise",
      "#training",
      "#workoutroutine",
      "#fitnessgirl",
      "#fitnessaddict",
      "#fitnesslife",
      "#gymtime",
      "#gains",
      "#fitspiration",
      "#healthyliving",
      "#active",
      "#fitgoals",
    ],
  },
  {
    name: "Travel & Adventure",
    category: "Travel",
    icon: "Plane",
    color: "blue",
    description: "Travel, exploration, and adventures",
    hashtags: [
      "#travel",
      "#travelblogger",
      "#travelgram",
      "#instatravel",
      "#wanderlust",
      "#adventure",
      "#explore",
      "#traveltheworld",
      "#traveladdict",
      "#travelphotography",
      "#travelholic",
      "#travelbug",
      "#travellife",
      "#travelmore",
      "#goexplore",
      "#adventuretime",
      "#exploremore",
      "#passportready",
      "#worldtraveler",
      "#globetrotter",
      "#vacation",
      "#holiday",
      "#trip",
      "#traveling",
      "#travelling",
      "#tourist",
      "#tourism",
      "#beautifuldestinations",
      "#bucketlist",
      "#wanderer",
    ],
  },
  {
    name: "Beauty & Makeup",
    category: "Beauty",
    icon: "Sparkles",
    color: "purple",
    description: "Beauty, makeup, and skincare",
    hashtags: [
      "#beauty",
      "#beautyblogger",
      "#makeup",
      "#makeuplover",
      "#makeupaddict",
      "#makeupjunkie",
      "#makeupoftheday",
      "#motd",
      "#beautygram",
      "#instabeauty",
      "#makeuplife",
      "#makeupartist",
      "#mua",
      "#skincare",
      "#skincareroutine",
      "#glam",
      "#glowup",
      "#beautytips",
      "#makeuptutorial",
      "#makeuplook",
      "#makeupinspo",
      "#beautyproducts",
      "#makeupobsessed",
      "#makeuplovers",
      "#beautycommunity",
      "#beautylover",
      "#selfcare",
      "#beautyessentials",
      "#makeupgoals",
      "#beautyaddict",
    ],
  },
  {
    name: "Food & Foodie",
    category: "Food",
    icon: "Coffee",
    color: "orange",
    description: "Food, recipes, and culinary delights",
    hashtags: [
      "#food",
      "#foodie",
      "#foodporn",
      "#foodblogger",
      "#instafood",
      "#foodstagram",
      "#foodphotography",
      "#foodlover",
      "#foodgasm",
      "#delicious",
      "#yummy",
      "#tasty",
      "#foodiesofinstagram",
      "#foodies",
      "#foodpics",
      "#foodblog",
      "#homemade",
      "#cooking",
      "#recipe",
      "#recipes",
      "#eats",
      "#foodart",
      "#foodstyling",
      "#eatlocal",
      "#healthyfood",
      "#cleaneating",
      "#foodcoma",
      "#nomnom",
      "#eatingfortheinsta",
      "#foodheaven",
    ],
  },
  {
    name: "Photography & Content",
    category: "Photography",
    icon: "Camera",
    color: "indigo",
    description: "Photography and content creation",
    hashtags: [
      "#photography",
      "#photographer",
      "#photooftheday",
      "#photo",
      "#picoftheday",
      "#instagood",
      "#instadaily",
      "#instapic",
      "#contentcreator",
      "#creator",
      "#createcontent",
      "#socialmedia",
      "#influencer",
      "#content",
      "#photoshoot",
      "#photogram",
      "#photooftheweek",
      "#instamoment",
      "#capture",
      "#beautiful",
      "#aesthetics",
      "#visualsoflife",
      "#creativelife",
      "#creativityfound",
      "#makersmovement",
      "#creatives",
      "#createeveryday",
      "#creativemind",
      "#visualart",
      "#artofvisuals",
    ],
  },
  {
    name: "Engagement Boosters",
    category: "Engagement",
    icon: "TrendingUp",
    color: "green",
    description: "High-engagement and viral potential hashtags",
    hashtags: [
      "#viral",
      "#trending",
      "#explorepage",
      "#explore",
      "#fyp",
      "#foryou",
      "#foryoupage",
      "#instagood",
      "#instadaily",
      "#reels",
      "#reelsinstagram",
      "#reelitfeelit",
      "#reelsvideo",
      "#instagram",
      "#insta",
      "#like4like",
      "#likeforlikes",
      "#follow",
      "#followme",
      "#followforfollowback",
      "#comment",
      "#share",
      "#engagement",
      "#discover",
      "#featured",
      "#popular",
      "#viralvideos",
      "#viralreels",
      "#trendingvideo",
      "#trendingreels",
    ],
  },
  {
    name: "Motivation & Quotes",
    category: "Inspiration",
    icon: "Heart",
    color: "rose",
    description: "Motivational and inspirational content",
    hashtags: [
      "#motivation",
      "#motivational",
      "#motivated",
      "#inspiration",
      "#inspire",
      "#inspirational",
      "#quotes",
      "#quotestoliveby",
      "#dailyquotes",
      "#quotesdaily",
      "#motivationalquotes",
      "#inspirationalquotes",
      "#lifequotes",
      "#quoteoftheday",
      "#qotd",
      "#mindset",
      "#positivity",
      "#positivevibes",
      "#positive",
      "#goodvibes",
      "#selfimprovement",
      "#selflove",
      "#personalgrowth",
      "#growthmindset",
      "#successmindset",
      "#believeinyourself",
      "#youcandoit",
      "#nevergiveup",
      "#keepgoing",
      "#dreambig",
    ],
  },
];

// POST initialize default hashtag sets
export async function POST() {
  try {
    const { userId } = await auth();

    if (!userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Check if user already has hashtag sets
    const existingSets = await prisma.hashtagSet.findMany({
      where: { clerkId: userId },
    });

    if (existingSets.length > 0) {
      return NextResponse.json(
        { error: "User already has hashtag sets" },
        { status: 400 }
      );
    }

    // Create all default hashtag sets
    const sets = await Promise.all(
      DEFAULT_HASHTAG_SETS.map((set, index) =>
        prisma.hashtagSet.create({
          data: {
            clerkId: userId,
            name: set.name,
            category: set.category,
            description: set.description,
            icon: set.icon,
            color: set.color,
            hashtags: set.hashtags,
            order: index,
          },
        })
      )
    );

    return NextResponse.json({ sets });
  } catch (error) {
    console.error("Error initializing hashtag sets:", error);
    return NextResponse.json(
      { error: "Failed to initialize hashtag sets" },
      { status: 500 }
    );
  }
}
